---

# (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: include default variables
  include_vars: "../vars/main.yml"
  tags: buildah

- name: include release specific variables
  include_vars: "{{ lookup('first_found', _params) }}"
  vars:
    _params:
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "../vars"
  ignore_errors: true
  tags: buildah

- name: include release specific tasks
  include_tasks: "{{ lookup('first_found', _params) }}"
  vars:
    _params:
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "."
  ignore_errors: true
  tags: buildah

- name: prepare directories
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
    state: "{{ item.state | default('directory') }}"
  loop:
    - { dest: "/usr/local/bin" }
    - { dest: "/usr/local/share/bash-completion/completions" }
    - { dest: "{{ buildah_download.dest | dirname }}" }
  tags: buildah

- name: download archive
  vars:
    ansible_python_interpreter: "python3"
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    checksum: "{{ item.checksum }}"
    timeout: 300
  loop:
    - "{{ buildah_download }}"
  register: get_url_result
  until: get_url_result is succeeded
  tags: buildah

- name: build package
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  shell: |
    set -o pipefail
    TMP_DIR="$(mktemp -d)" \
      && export GOPATH=$TMP_DIR \
      && export PATH="$GOPATH/bin:$PATH" \
      && cd $GOPATH \
      && go get -u github.com/cpuguy83/go-md2man \
      && mkdir -p $GOPATH/src/github.com/containers/buildah \
      && cd $GOPATH/src/github.com/containers/buildah \
      && tar -zx -C . -f {{ buildah_download.dest }} --strip-components=1 \
      && export GIT_COMMIT={{ buildah_version }} \
      && make BUILDTAGS='apparmor seccomp selinux btrfs_noversion exclude_graphdriver_btrfs' \
      && make install \
      && make install.completions \
      && rm -rf $TMP_DIR
  args:
    executable: "/bin/bash"
  when: get_url_result is changed
  register: result
  until: result is succeeded
  tags: buildah

- name: prepare files
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
    state: "{{ item.state | default('file') }}"
  loop:
    - { dest: "/usr/local/bin/buildah", mode: "0755" }
    - { dest: "/usr/local/share/bash-completion/completions/buildah" }
  tags: buildah
